### ISSUE TITLE
[BUG]: OpenQA.Selenium.WebDriverTimeoutException: Timed out after 10 seconds

### ISSUE THREAD

**Issue by HexaSq** [nogiszd/xiaomi-note-exporter#21]
**Describe the bug**
The cmd gave this error after 250 notes.  

**To Reproduce**
[Same as instructions]

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem
![Miui](https://github.com/nogiszd/xiaomi-note-exporter/assets/83910328/53448ae4-45e3-4f2d-981b-30e27ba2c2fa)
.

**Current environment (please complete the following information):**
 - Current Chrome version [latest]
 - Os : Win 10 Home 64 bit
 -

**Additional context**
ull Logs : Parsed 250 notes out of 771... (32%)
Please report this error on GitHub

OpenQA.Selenium.WebDriverTimeoutException: Timed out after 10 seconds
 ---> OpenQA.Selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//div[contains(@class, 'origin-title')]/div"}
  (Session info: chrome=123.0.6312.106); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.By.<.ctor>b__11_0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.WebDriver.FindElement(By by)
   at xiaomiNoteExporter.Program.<>c.<Main>b__10_8(IWebDriver e)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition, CancellationToken token)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Support.UI.DefaultWait`1.ThrowTimeoutException(String exceptionMessage, Exception lastException)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition, CancellationToken token)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
   at xiaomiNoteExporter.Program.Main()

Thanks :)

**Comment by HexaSq** [comment]
[Solved]
I tried it again n again n was finally able to finish the export! Thanks, God bless u my bro ❤
How?
>When u login after that open some random notes to the bottom so that they are in cache & don't need active internet/new ram to open
>Make sure to have good internet
>Sometimes note might get stuck, use mouse scroll button or click the note again
>Keep cmd on right and notes on left like in split screen
>Power plan :High performance

**Comment by nogiszd** [comment]
Hi @HexaSq,
you should look into [this fork](https://github.com/aviv926/xiaomi-note-exporter). 
He made scripts in Python that convert exported notes into other formats. 

But unfortunately I'm not aware if it is possible to import them into Google Keep.

**Comment by HexaSq** [comment]
I made a script which can automatically import notes to Google keep. I would post it here.
I might also make a youtube video on how to import notes from mi notes & paste it in Google keep. Would mention ur excellent work there.

**Comment by nogiszd** [comment]
You can make a fork and include your scripts, or make a pull request then I will include your script into this repository.
About the video, I don't mind. But as I stated in readme, I don't have time to maintain this project, so eventual fixes are delayed.

**Comment by nogiszd** [comment]
If you manage to implement new features, please make a pull request.
