### ISSUE TITLE
Fail to parse time out after 10 sec

### ISSUE THREAD

**Issue by xATL4S** [nogiszd/xiaomi-note-exporter#4]
Message appears in terminal:

Parsed 203 notes out of 548... (37%)
Please report this error on GitHub

OpenQA.Selenium.WebDriverTimeoutException: Timed out after 10 seconds
   at OpenQA.Selenium.Support.UI.DefaultWait`1.ThrowTimeoutException(String exceptionMessage, Exception lastException)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition, CancellationToken token)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
   at xiaomiNoteExporter.Program.Main()

Running latest version of chrome: Version 110.0.5481.178
.net framework 6.0
Server 2022 vm

Have repeated this 3x now. First one failed with same error message at about 197? next 2 attempts were both at 203.

Hope this helps

**Comment by nogiszd** [comment]
Hi, thanks for telling about this issue.

Does this note contains any unusual characters, whitespaces or is it blank?

**Comment by xATL4S** [comment]
Sorry for taking so long to respond,

As far as I know, it should just be a list of websites.

**Comment by nogiszd** [comment]
Did you use this app on server/cloud virtual machine?

**Comment by xATL4S** [comment]
Virtual machine

**Comment by sfat-llc** [comment]
I got something similar
`Parsed 218 notes out of 271... (80%)
Please report this error on GitHub

OpenQA.Selenium.WebDriverTimeoutException: Timed out after 10 seconds
 ---> OpenQA.Selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//div[contains(@class, 'origin-title')]/div"}
  (Session info: headless chrome=113.0.5672.127)
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.By.<.ctor>b__11_0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.WebDriver.FindElement(By by)
   at xiaomiNoteExporter.Program.<>c.<Main>b__10_7(IWebDriver e)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition, CancellationToken token)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Support.UI.DefaultWait`1.ThrowTimeoutException(String exceptionMessage, Exception lastException)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition, CancellationToken token)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
   at xiaomiNoteExporter.Program.Main()`

**Comment by pwrsoft** [comment]
In my casу this error happens when the note is "Association map" type.
This feature appeared in 2020 and is overviewed here:
https://www.xiaomist.com/2020/11/the-xiaomi-notes-application-now-allows.html

@nogiszd Is it possible to skip unsupported note types while exporting instead of throwing an exeption, thanks!

PS: It would be helpful to leave some kind of comment in exported notes .md file (maybe it can unparsed note's body or date marker or even "[SKIPPED NOTE]" text, which will make possible to find these non-exported notes after import.

**Comment by nogiszd** [comment]
@pwrsoft, thank you for targeting the issue. 
It might be that some note types are unsupported and editor element that contains id 'origin-title' is not existent.

@sfat-llc - is your note of other type than regular text note? 

Nonetheless, I will implement fallback for other note types, and maybe in the future I will tackle parsing them.

**Comment by nogiszd** [comment]
The issue with unsupported note types was resolved in [latest release](https://github.com/nogiszd/xiaomi-note-exporter/releases/latest).

At the end i went for @pwrsoft's suggestion to mark note as skipped with it's creation date.
In the future i might go for complete parsing of "mind-maps".
